org: studyaws
service: chaparral

build:
  esbuild:
    minify: true
    bundle: true
    sourcemap: false
    exclude:
      - "@aws-sdk/*"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  architecture: arm64
  deploymentMethod: direct
  environment:
    COGNITO_CLIENT_ID: !Ref ChaparralUserPoolClient

resources:
  Resources:
    ChaparralUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ChaparralUserPool
        MfaConfiguration: OFF
        AutoVerifiedAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        UsernameAttributes:
          - email
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
            TemporaryPasswordValidityDays: 10
        Schema:
          - Name: given_name
            Mutable: true
            Required: true
            AttributeDataType: String
          - Name: phone_number
            Mutable: true
            Required: true
            AttributeDataType: String
          - Name: email
            Mutable: true
            Required: true
            AttributeDataType: String
    ChaparralUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ChaparralUserPoolClient
        UserPoolId: !Ref ChaparralUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        TokenValidityUnits:
          AccessToken: hours
          RefreshToken: hours
        AccessTokenValidity: 3
        RefreshTokenValidity: 1440 #60 days

functions:
  signUp:
    handler: src/functions/auth/signUp.handler
    events:
      - httpApi:
          path: /auth/sign-up
          method: POST
  accountConfirmation:
    handler: src/functions/auth/accountConfirmation.handler
    events:
      - httpApi:
          method: POST
          path: /auth/account-confirmation
  signIn:
    handler: src/functions/auth/signIn.handler
    events:
      - httpApi:
          method: POST
          path: /auth/sign-in
  refreshToken:
    handler: src/functions/auth/refreshToken.handler
    events:
      - httpApi:
          method: POST
          path: /auth/refresh-token
